AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda GET-ITEMS usando imagen ECR"

Resources:
  GetItemsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get_items
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/inventory-no-acoplated-app:get_group"
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Timeout: 10
      MemorySize: 128
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMO_TABLE: products

Outputs:
  LambdaName:
    Value: !Ref GetItemsLambda