AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda UPDATE usando imagen ECR"

Resources:
  UpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: update
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/my-ecr-desacoplado:update"
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Timeout: 10
      MemorySize: 128
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMO_TABLE: MiTablaEjemplo

Outputs:
  LambdaName:
    Value: !Ref UpdateLambda