AWSTemplateFormatVersion: '2010-09-09'
Description: Tabla mínima de DynamoDB con tres atributos

Resources:
  MiTablaDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MiTablaEjemplo
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: Nombre
          AttributeType: S
        - AttributeName: fecha
          AttributeType: S
        - AttributeName: cantidad
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: categoria
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
