AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue mínimo de aplicación CRUD con ECS, Docker y DynamoDB usando NLB interno y API Gateway con VPC Link

Parameters:
  ImageUri:
    Type: String
    Description: URI de la imagen Docker en ECR (ej. 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app:latest)

  VpcId:
    Type: String
    Description: ID de la VPC existente

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets públicas (no usadas pero necesarias si quieres mantener referencia)

  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets privadas para las tareas ECS y el NLB interno

  ContainerPort:
    Type: Number
    Default: 80
    Description: Puerto del contenedor
  
  DynamoTableName:
    Type: String
    Default: my-app-table
    Description: Nombre de la tabla DynamoDB que usará la aplicación

Resources:
  # IAM Roles
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: "*"

  # ECS Cluster
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-app-cluster

  # ECS Task Definition
  MyECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-app-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: my-app-container
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: DYNAMO_TABLE
              Value: !Ref DynamoTableName
            - Name: AWS_REGION
              Value: !Ref "AWS::Region"

  # Security Group para ECS Tasks
  TaskSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite tráfico solo desde NLB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 10.0.0.0/16  # Ajusta según tu CIDR de VPC

  # NLB interno
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-app-nlb
      Scheme: internal
      Type: network
      Subnets: !Ref PrivateSubnets

  # Target Group para NLB
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-app-tg
      Port: !Ref ContainerPort
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckProtocol: TCP
      HealthCheckPort: !Ref ContainerPort

  # ECS Service
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      ServiceName: my-app-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref MyECSTask
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref TaskSG
          Subnets: !Ref PrivateSubnets
      LoadBalancers:
        - ContainerName: my-app-container
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AppTargetGroup

  # API Gateway
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyAppAPI
      Description: API CRUD para items en DynamoDB

  # VPC Link
  MyVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: MyAppVpcLink
      TargetArns:
        - !Ref AppLoadBalancer

  # API Resources
  ItemsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: items

  ItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !Ref ItemsResource
      PathPart: "{id}"

  # API Methods
  PostItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: POST
        Uri: !Sub "http://${AppLoadBalancer.DNSName}:${ContainerPort}/items"
        ConnectionType: VPC_LINK
        VpcLinkId: !Ref MyVpcLink

  GetItems:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${AppLoadBalancer.DNSName}:${ContainerPort}/items"
        ConnectionType: VPC_LINK
        VpcLinkId: !Ref MyVpcLink

  GetItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${AppLoadBalancer.DNSName}:${ContainerPort}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id
        ConnectionType: VPC_LINK
        VpcLinkId: !Ref MyVpcLink

  PutItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: PUT
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP
        IntegrationHttpMethod: PUT
        Uri: !Sub "http://${AppLoadBalancer.DNSName}:${ContainerPort}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id
        ConnectionType: VPC_LINK
        VpcLinkId: !Ref MyVpcLink

  DeleteItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP
        IntegrationHttpMethod: DELETE
        Uri: !Sub "http://${AppLoadBalancer.DNSName}:${ContainerPort}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id
        ConnectionType: VPC_LINK
        VpcLinkId: !Ref MyVpcLink

  # Deployment y Stage
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostItem
      - GetItems
      - GetItem
      - PutItem
      - DeleteItem
    Properties:
      RestApiId: !Ref MyApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref MyApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

Outputs:
  NlbDNS:
    Description: DNS del Network Load Balancer interno
    Value: !GetAtt AppLoadBalancer.DNSName

  ApiUrl:
    Description: URL base del API Gateway
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
