AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue mínimo de aplicación CRUD con ECS, Docker y DynamoDB

Parameters:
  ImageUri:
    Type: String
    Description: URI de la imagen Docker en ECR (ej. 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app:latest)

  VpcId:
    Type: String
    Description: ID de la VPC existente

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets públicas para el Load Balancer

  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets privadas para las tareas ECS

  ContainerPort:
    Type: Number
    Default: 80
    Description: Puerto del contenedor
  
  DynamoTableName:
    Type: String
    Default: my-app-table
    Description: Nombre de la tabla DynamoDB que usará la aplicación

Resources:
  # IAM Roles

  # Rol para ejecutar tareas ECS (obligatorio para Fargate)
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # Rol para que la tarea ECS acceda a DynamoDB (opcional si no usa DB)
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: "*"

  # Cluster ECS (obligatorio)
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-app-cluster
# Definición del contenedor con las tareas a ejecutar, con los recursos CPU y Memoria necesarios
  MyECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-app-task
      Cpu: '256' #obligatorio para Fargate
      Memory: '512' #obligatorio para Fargate
      NetworkMode: awsvpc #obligatorio para Fargate solo puede ser awsvpc
      RequiresCompatibilities: #Necesario para decirle que vas a usar Fargate
        - FARGATE
      ContainerDefinitions:
        - Name: my-app-container
          Image: <TU_REPOSITORIO_DOCKER> 
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: DYNAMO_TABLE
              Value: <NOMBRE_DE_TU_TABLA>
            - Name: AWS_REGION
              Value: us-east-1

 # SG para el ALB (obligatorio si es internet-facing)
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite tráfico HTTP desde Internet al ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # SG para ECS Tasks (obligatorio para controlar acceso)
  TaskSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite tráfico solo desde el ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSG

  # Application Load Balancer
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-app-alb
      Scheme: internet-facing #hace que sea accesible desde internet
      Subnets: !Ref PublicSubnets #OBLIGATORIO: donde se despliega el LB
      SecurityGroups:
        - !Ref LoadBalancerSG

  # Target Group para ECS
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-app-tg #si no se pone AWS genera el nombre por su cuaneta
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip #es necesario para usar Fargate
      VpcId: !Ref VpcId
      HealthCheckPath: /health #opcional pero recomendable

  # Listener del Load Balancer
  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer #OBLIGATORIO
      Port: 80                              #OBLIGATORIO
      Protocol: HTTP                        #OBLIGATORIO
      DefaultActions: #DEFINE QUE HACER CON EL TRÁFICO
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster                # OBLIGATORIO Cluster donde correrán las tareas
      ServiceName: my-app-service               # OPCIONAL puedes dejar que AWS genere un nombre
      LaunchType: FARGATE                       # OBLIGATORIO tipo de ejecución
      DesiredCount: 1                           # OBLIGATORIO número inicial de tareas
      TaskDefinition: !Ref MyECSTask            # OBLIGATORIO la Task Definition que correrá
      NetworkConfiguration:                     # OBLIGATORIO para Fargate
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED             # OPCIONAL DISABLED si estás en subnets privadas
          SecurityGroups:
            - !Ref TaskSG                       # OBLIGATORIO SG que controla acceso a la tarea
          Subnets: !Ref PrivateSubnets          # OBLIGATORIO subnets donde correrán las tareas
      LoadBalancers:                             # OPCIONAL pero necesario si quieres exponer la tarea via ALB
        - ContainerName: my-app-container
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AppTargetGroup

  MyApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyAppAPI
        Description: API CRUD para items en DynamoDB
  
  #PARA DEFINIR LAS RUTAS /items y /items/{id}
  ItemsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: items

  ItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !Ref ItemsResource
      PathPart: "{id}"

  # POST /items
  PostItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "http://${AppLoadBalancer.DNSName}/items"

  # GET /items
  GetItems:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${AppLoadBalancer.DNSName}/items"

  # GET /items/{id}
  GetItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${AppLoadBalancer.DNSName}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id

  # PUT /items/{id}
  PutItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: PUT
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: PUT
        Uri: !Sub "http://${AppLoadBalancer.DNSName}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id

  # DELETE /items/{id}
  DeleteItem:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref ItemResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: DELETE
        Uri: !Sub "http://${AppLoadBalancer.DNSName}/items/{id}"
        RequestParameters:
          integration.request.path.id: method.request.path.id

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostItem
      - GetItems
      - GetItem
      - PutItem
      - DeleteItem
    Properties:
      RestApiId: !Ref MyApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref MyApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

Outputs:
  LoadBalancerDNS:
    Description: DNS del Application Load Balancer
    Value: !GetAtt AppLoadBalancer.DNSName

  ApiUrl:
    Description: URL base del API Gateway
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
